# If you have OpenSSL installed, we recommend updating
# the following line to use 'https'
source 'http://rubygems.org'

gem 'middleman', '~>3.2.0'

gem 'nokogiri'
gem 'redcarpet'
gem 'pygments.rb', :require => 'pygments'
